name: Setup Python in Docker
on: [push]
jobs:
    setup-python-in-docker:
        runs-on: ubuntu-latest
        # container:
            # image: guptapankaj831/github-actions-examples@main
        steps:
            # - name: Run Action
            - uses: actions/checkout@v4
            - uses: guptapankaj831/github-actions-examples@main
            - run: black .
            - run: flake8 .
            # - run: poetry run bandit --ini .bandit -r
            # - run: pytest
