name: Setup Python in Docker
on: [push]
jobs:
    setup-python-in-docker:
        runs-on: ubuntu-latest
        container:
            image: python:latest # guptapankaj831/github-actions-examples/Dockerfile
        steps:
            # - name: Run Action
            #   uses: guptapankaj831/github-actions-examples@main
            - uses: actions/checkout@v4
            - run: pip install flake8 pytest black poetry
            - run: black .
            - run: flake8 .
