name: Test Python Code
on: [push]
jobs:
    test_code:
        runs-on: ubuntu-latest
        container:
          image: python:latest
        steps:
            - name: check repository
              uses: actions/checkout@v4

            - name: install packages
              run: | 
                pip install flake8 pytest black

            - name: Lint with flake8
              run: |
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 jupytext tests
                flake8 . --count --exit-zero --max-complexity=10 --statistics

